//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PilotTask
    {
        public int Id { get; set; }
        public Nullable<int> Profile_ID { get; set; }
        public string TaskName { get; set; }
        public string TaskDiscription { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
